# -*- coding: utf-8 -*-
"""QA_Banco_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRxFToR4sYNs2ZSAJa3d_x8rd6r92Nl-

Banco do Stark
"""

class Conta:
    def __init__(self, titular):
        self.titular = titular
        self.saldo = 0
        self.extrato = []

print('Classe Conta criada')

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return

        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

print('Classe Banco criada')

class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular):
        if titular in self.contas:
            print('Conta já existe')
            return
        self.contas[titular] = Conta(titular)
        print('Conta criada para', titular)

    def depositar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito',valor))

        print('Depósito realizado:',valor)

    def sacar(self, titular, valor):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        if self.contas[titular].saldo < valor:
            print('Saldo insuficiente')
            return

        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque',valor))

        print('Saque realizado:',valor)

    def saldo(self, titular):
        if titular not in self.contas:
            print('Conta não encontrada')
            return

        print('Saldo de', titular, '=', self.contas[titular].saldo)

print('Operações adicionadas')

banco = BancoDoStark()
print('Banco do Stark em Funcionamento')

"""Testes

Caminho Feliz
"""

banco.criar_conta('Tony Stark')

banco.criar_conta('Tony Stark')

banco.depositar('Tony Stark', 100000)

banco.saldo('Tony Stark')

banco.sacar('Tony Stark', 50000)

banco.saldo('Tony Stark')

banco.criar_conta('Steve Rogers')
banco.criar_conta('Bruce Banner')
banco.criar_conta('Thor')
banco.criar_conta('Natasha Romanoff')

banco.depositar('Steve Rogers', 2000)
banco.depositar('Bruce Banner', 3000)
banco.depositar('Thor', 5000)
banco.depositar('Natasha Romanoff', 10000)

banco.sacar('Steve Rogers', 350)

banco.saldo('Steve Rogers')

"""Testes Negativos - QA"""

banco.depositar('Steve Rogers', 0)

banco.depositar('Steve Rogers', -450)

banco.depositar('Steve Rogers', 999999999999999999999999999999999999999999999999999999999999)

banco.sacar('Tony Stark',200000)

banco.sacar('Tony Stark', Mil Reais)

banco.sacar('Tony Stark', -50000)