# -*- coding: utf-8 -*-
"""JJosé_5MA_Atividade_QA_Banco_do_Stark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Z2g82YME7xyY4J_E01LRw40G553kRJS

# Atividade em Aula — QA Manual
## Banco do Stark

**Objetivo da atividade:**
- Transformar a execução prática em **Casos de Teste **
- Registrar pelo menos **3 Bug Report profissional **

**Como vamos trabalhar:**
1. Execute as células na ordem.
2. Observe os resultados dos testes (saídas no notebook).
3. Preencha os templates (Casos de Teste e Bug Report) nas células indicadas.

**Entrega (durante a aula):**
- Mínimo **3 Casos de Teste** preenchidos (com esperado/obtido e status).
- Mínimo **1 Bug Report** preenchido (com passos reproduzíveis e evidência).

## Regras esperadas (Requisitos do Banco)
Considere que o comportamento correto do sistema seria:
1. **Titular** não pode ser vazio (nem só espaços).
2. **Depósito**: valor deve ser **> 0**.
3. **Saque**: valor deve ser **> 0** e **não pode exceder** o saldo.
4. **Transferência**: valor deve ser **> 0**, **destino deve existir**, e **não pode transferir para si mesmo**.
5. **Saldo** nunca pode ficar negativo.
6. **Extrato** deve registrar corretamente as operações.
"""

# =========================================
# APP: Banco do Stark (simples)
# =========================================

class Conta:
    def __init__(self, titular: str):
        self.titular = titular
        self.saldo = 0.0
        self.extrato = []


class BancoDoStark:
    def __init__(self):
        self.contas = {}

    def criar_conta(self, titular: str):
        if titular in self.contas:
            print('ERRO - Conta já existe:', titular)
            return
        self.contas[titular] = Conta(titular)
        print('OK - Conta criada para:', titular)

    def depositar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        # Observação: validações intencionalmente simples (para QA encontrar problemas)
        self.contas[titular].saldo += valor
        self.contas[titular].extrato.append(('deposito', valor))
        print('OK - Depósito realizado:', valor)

    def sacar(self, titular: str, valor: float):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        if self.contas[titular].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[titular].saldo -= valor
        self.contas[titular].extrato.append(('saque', valor))
        print('OK - Saque realizado:', valor)

    def transferir(self, origem: str, destino: str, valor: float):
        if origem not in self.contas:
            print('ERRO - Conta origem não encontrada')
            return
        if destino not in self.contas:
            print('ERRO - Conta destino não encontrada')
            return
        if self.contas[origem].saldo < valor:
            print('ERRO - Saldo insuficiente')
            return
        self.contas[origem].saldo -= valor
        self.contas[destino].saldo += valor
        self.contas[origem].extrato.append(('transferencia_saida', valor))
        self.contas[destino].extrato.append(('transferencia_entrada', valor))
        print('OK - Transferência realizada:', valor)

    def saldo_atual(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('SALDO', titular, '=', self.contas[titular].saldo)

    def mostrar_extrato(self, titular: str):
        if titular not in self.contas:
            print('ERRO - Conta não encontrada:', titular)
            return
        print('EXTRATO:', titular)
        for item in self.contas[titular].extrato:
            print(' -', item)


banco = BancoDoStark()
print('Banco do Stark carregado!')

"""Execute esta célula para gerar um cenário inicial e, em seguida, alguns testes negativos.

**Sua tarefa será:**
- Observar a saída
- Criar **Casos de Teste** com base no que foi executado
- Registrar pelo menos **1 Bug Report**

"""

# =========================================
# CENÁRIO INICIAL (caminho feliz)
# =========================================

print('=== CRIAR CONTAS ===')
banco.criar_conta('tony')
banco.criar_conta('pepper')
banco.criar_conta('banner')

print('\n=== DEPÓSITOS ===')
banco.depositar('tony', 1000)
banco.depositar('pepper', 500)

print('\n=== SALDOS ===')
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== SAQUE ===')
banco.sacar('tony', 200)
banco.saldo_atual('tony')

print('\n=== TRANSFERÊNCIA ===')
banco.transferir('tony', 'pepper', 100)
banco.saldo_atual('tony')
banco.saldo_atual('pepper')

print('\n=== EXTRATO (tony) ===')
banco.mostrar_extrato('tony')

print('\n=================================')
print('TESTES NEGATIVOS (QA)')
print('=================================\n')

print('Teste N1 - Depósito com valor zero')
banco.depositar('tony', 0)

print('\nTeste N2 - Depósito negativo')
banco.depositar('tony', -100)

print('\nSaldo após depósitos inválidos')
banco.saldo_atual('tony')

print('\nTeste N3 - Saque acima do saldo')
banco.sacar('tony', 100000)

print('\nTeste N4 - Transferência para conta inexistente')
banco.transferir('tony', 'thor', 50)

print('\nTeste N5 - Consulta de conta inexistente (saldo)')
banco.saldo_atual('natasha')

print('\nTeste N6 - Consulta de conta inexistente (extrato)')
banco.mostrar_extrato('natasha')

"""# PARTE 04 — Casos de Teste (atividade)
Agora você vai documentar **3 Casos de Teste** com base no que você observou.

### Regras
- Cada caso precisa ter **Resultado esperado** e **Resultado obtido**.
- Status deve ser **Pass** ou **Fail**.
- Evidência: copie um trecho da saída do notebook (ou descreva exatamente o que apareceu).

### Sugestões de temas (você escolhe 3)
- Depósito com valor 0
- Depósito negativo
- Saque acima do saldo
- Transferência para conta inexistente
- Consulta de saldo de conta inexistente

## Template — Caso de Teste 1
**ID:** CT-001  
**Título/Objetivo:**  CRIAR CONTAS
**Pré-condição:** banco rodando
**Passos:**  
1. colocar um **nome**   
2. criar a conta
**Resultado esperdo:**  criar a conta se for um nome valido(não pode ser so numeros ou simbolos)
**Resultado obtido:**  criada
**Status (Pass/Fail):** Pass
**Evidência:**  OK - Conta criada para: 123
OK - Conta criada para: @@@

## Template — Caso de Teste 2
**ID:** CT-002  
**Título/Objetivo:**  Teste N2 - Depósito negativo
**Pré-condição:**  banco  rodando
**Passos:**  
1.  criar uma conta
2. ver o extrato  
3.  depositar
**Resultado esperado:**  falhar,deposito negativo não existe
**Resultado obtido:**  passou como se fosse normal
**Status (Pass/Fail):**  pass
**Evidência:**  Teste N2 - Depósito negativo
OK - Depósito realizado: -100

## Template — Caso de Teste 3
**ID:** CT-003  
**Título/Objetivo:**  Teste N7 - Saque negativo

**Pré-condição:**  banco rodando
**Passos:**  
1.  criar conta
2.  verificar extrato
3.  sacar
**Resultado esperado:**  falhar, pois não existe saque negativo
**Resultado obtido:**  passou "normal"
**Status (Pass/Fail):**  pass
**Evidência:**  Teste N7 - Saque negativo
OK - Saque realizado: -10000

# PARTE 05 — Bug Report (atividade)
Agora escolha **3 falhas** que você observou e registre o **Bug Report profissional** de cada uma delas.

### Dicas
- O bug deve ser **reproduzível** (passos claros)
- Inclua o **Resultado esperado** e o **Resultado obtido**
- Inclua **evidência** (saída do notebook)

**Sugestões de bugs (se apareceram na sua execução):**
- Sistema aceita depósito com valor 0
- Sistema aceita depósito com valor negativo

## Template — Bug Report
**Título:**  deposito de valor negativo
**Severidade (Baixa/Média/Alta):** media
**Prioridade (Baixa/Média/Alta):**  media
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  não deveria ser possivel depositar valores negativos

**Passos para reproduzir:**  
1.  banco rodando
2.  criar a conta
3.  depositar o valor negativo

**Resultado esperado:** falhar  
**Resultado obtido:**  passou
**Evidência:**  Teste N8 - deposito negativo
OK - Depósito realizado: -10000
**Impacto/Risco:**  alta(caso  quebre o sistema)

## Template — Bug Report
**Título:**  saque de valor negativo
**Severidade (Baixa/Média/Alta):**  alta
**Prioridade (Baixa/Média/Alta):**  media
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  não deveria poder ser feito saques de valores negativos,caso realmente seja sacado uma quantia isso seria um problema

**Passos para reproduzir:**  
1.  banco rodando
2.  criar a conta
3.  sacar o valor negativo

**Resultado esperado:**  falhar
**Resultado obtido:**  passou como se fosse normal
**Evidência:**  print('\nTeste N7 - Saque negativo')
banco.sacar('tony', -10000)
**Impacto/Risco:**  medio/alto caso seja realizado algum saque

## Template — Bug Report
**Título:**  nome irregular de comta
**Severidade (Baixa/Média/Alta):**  baixa
**Prioridade (Baixa/Média/Alta):**  baixa
**Ambiente:** Google Colab / Python 3.x / Banco do Stark  

**Descrição:**  contas sendo criadas sem um nome,mas sim como simbolos e numeros

**Passos para reproduzir:**  
1.  banco rodando
2.  colocar literalmente qualquer numero/simbolo no nome da conta
3.  criar conta

**Resultado esperado:**  falhar
**Resultado obtido:**  passou
**Evidência:**  OK - Conta criada para: 123 OK - Conta criada para: @@@
**Impacto/Risco:**  baixa

## (Opcional) Rodar novos testes
Use esta célula para rodar testes adicionais e fortalecer suas evidências.
Você pode criar novos casos de teste e/ou registrar mais bugs.
"""

# Escreva seus testes aqui (exemplos abaixo)

# banco.depositar('pepper', -1)
# banco.sacar('pepper', 0)
# banco.transferir('pepper', 'banner', 999999)

#print('Pronto! Execute seus testes aqui.')
banco.criar_conta('123')
banco.criar_conta('@@@')#ignora a saida,pois eu ja tinha feito la encima

print('\nTeste N7 - Saque negativo')
banco.sacar('tony', -10000)
print('\nTeste N8 - deposito negativo')
banco.depositar('tony', -10000)

"""## Critérios de avaliação (rápido)
- **Casos de teste:** passos claros + esperado/obtido + status + evidência
- **Bug report:** reproduzível + esperado/obtido + evidência + impacto

Quando terminar, avise o professor no chat.

"""