# -*- coding: utf-8 -*-
"""Danilo Souza Montenegro_95105_QA_SWAPI_atividade_grupo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRiGo0d94OCg9wPumiii4bylsBRZXTq_

# Atividade Prática — QA com APIs (SWAPI)

## Versão do aluno — com scripts base

**Tempo estimado:** 60 minutos  
**Ferramenta:** Google Colab  
**Formato:** em grupos de **2 a 4 componentes** ou, se preferirem, **individualmente**.  
**Objetivo:** investigar respostas de uma API, ajustar scripts simples e responder às perguntas como um QA.

### Instruções
Nesta atividade, vocês **não precisam criar tudo do zero**.  
Os scripts já estão prontos como base. A tarefa do grupo será:

1. **Executar** os blocos de código
2. **Alterar apenas o que for pedido**
3. **Observar os resultados**
4. **Responder às perguntas em Markdown**
5. **Discutir em grupo** quais validações um QA faria

### Entrega
Cada grupo pode entregar **um único notebook** com:
- nomes dos integrantes
- respostas das perguntas
- scripts ajustados
- asserts completados

Se alguém optar por fazer sozinho, pode entregar individualmente sem problema.
"""

import requests
import json

# -------------------------
# MODO DE SEGURANÇA (fallback)
# -------------------------
# Se a API não responder, o notebook usa dados locais
# para a atividade continuar funcionando.

DADOS_FALLBACK = {
    "https://swapi.dev/api/people/10/": {
        "name": "Obi-Wan Kenobi",
        "height": "182",
        "mass": "77",
        "eye_color": "blue-gray",
        "gender": "male",
        "url": "https://swapi.dev/api/people/10/"
    },
    "https://swapi.dev/api/people/13/": {
        "name": "Chewbacca",
        "height": "228",
        "mass": "112",
        "eye_color": "blue",
        "gender": "male",
        "url": "https://swapi.dev/api/people/13/"
    },
    "https://swapi.dev/api/planets/2/": {
        "name": "Alderaan",
        "climate": "temperate",
        "terrain": "grasslands, mountains",
        "population": "2000000000",
        "url": "https://swapi.dev/api/planets/2/"
    },
    "https://swapi.dev/api/starships/117/": {
        "name": "Millennium Falcon",
        "model": "YT-1300 light freighter",
        "manufacturer": "Corellian Engineering Corporation",
        "max_atmosphering_speed": "1050",
        "url": "https://swapi.dev/api/starships/10/"
    }
}

class RespostaLocal:
    def __init__(self, status_code, data):
        self.status_code = status_code
        self._data = data
        self.text = json.dumps(data, ensure_ascii=False)

    def json(self):
        return self._data

def buscar_endpoint(url):
    try:
        resposta = requests.get(url, timeout=10)
        if resposta.status_code == 200:
            return resposta, "online"
    except Exception:
        pass

    if url in DADOS_FALLBACK:
        return RespostaLocal(200, DADOS_FALLBACK[url]), "fallback local"

    return RespostaLocal(404, {"detail": "Not found"}), "fallback local"

print("Ambiente preparado com sucesso.")

"""## Identificação do grupo

- Integrante 1: Danilo Souza Montenegro
- Integrante 2:
- Integrante 3 (se houver):
- Integrante 4 (se houver):

## Parte 1 — Explorando a API

Nesta primeira parte, vocês vão consultar 4 endpoints.  
O trabalho do grupo será **alterar apenas a URL** em cada bloco, executar e observar o retorno.

### 1.1 Personagem 7

**Tarefa:** execute o script e observe:
- status code
- nome
- altura
- cor dos olhos
"""

url = "https://swapi.dev/api/people/7/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 7**

- Status code: 200
- Nome do personagem: Beru Whitesun lars
- Altura: - 165cm
- Cor dos olhos: - Azul
- O JSON parece completo? Sim

### 1.2 Personagem 27

**Tarefa:** neste bloco, troque apenas o endpoint se necessário, execute e observe o retorno.
"""

url = "https://swapi.dev/api/people/27/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Personagem 27**

- Status code: 200
- Nome do personagem: Ackbar
- Altura: 180cm
- Cor dos olhos: Laranja
- O JSON parece completo? Sim

### 1.3 Planeta 14

**Tarefa:** execute o bloco e observe:
- nome do planeta
- clima
- terreno
- população
"""

url = "https://swapi.dev/api/planets/14/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Planeta 14**

- Status code:200
- Nome do planeta: Kashyyyk
- Clima: Tropical
- Terreno: Selva, florestas, lagos, rios.
- População: 45000000
- O JSON parece completo? Sim

### 1.4 Nave 13

**Tarefa:** execute o bloco e observe:
- nome da nave
- modelo
- fabricante
- velocidade máxima em atmosfera
"""

url = "https://swapi.dev/api/starships/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print(json.dumps(dados, indent=4, ensure_ascii=False))

"""**Respostas do aluno — Nave 13**

- Status code:200
- Nome da nave:TIE Advanced x1
- Modelo: Twin Ion Engine Advanced x1
- Fabricante: Sienar Fleet Systems
- Velocidade máxima em atmosfera: 1200
- O JSON parece completo? Sim

## Parte 2 — Extraindo campos específicos

Agora você vai executar os scripts e **completar as respostas**.

### 2.1 Extraindo campos do personagem

**Tarefa:** execute o bloco e depois responda.
"""

url = "https://swapi.dev/api/people/10/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome:", dados["name"])
print("Altura:", dados["height"])
print("Cor dos olhos:", dados["eye_color"])
print("Gênero:", dados["gender"])

"""**Perguntas**
1. Qual campo foi usado para mostrar o nome?
2. Qual campo foi usado para mostrar a altura?
3. Se você fosse QA, quais desses campos validaria primeiro?

### 2.2 Extraindo campos do planeta

**Tarefa:** execute o bloco e complete as respostas.
"""

url = "https://swapi.dev/api/planets/14/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Nome do planeta:", dados["name"])
print("Clima:", dados["climate"])
print("Terreno:", dados["terrain"])
print("População:", dados["population"])

"""**Perguntas**
1. O campo população parece numérico? Não
2. O clima foi retornado corretamente? Sim
3. Se você fosse QA, o que validaria nesse planeta?

Se todos os campos esperados (nome, clima, etc) estão presentes.

Se o tipo de cada campo está correto: textos como string e população vindo como string numérica, não como número.

Se os valores fazem sentido para Kashyyyk.

## Parte 3 — Pensando como QA

Agora você vai trabalhar com validações simples.

### 3.1 Validações básicas

**Tarefa:** execute o bloco abaixo e depois escreva o que cada validação verifica.
"""

url = "https://swapi.dev/api/people/7/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Validação 1 - status 200:", response.status_code == 200)
print("Validação 2 - campo 'name' existe:", "name" in dados)
print("Validação 3 - nome não está vazio:", dados["name"] != "")
print("Validação 4 - campo 'height' existe:", "height" in dados)

"""**Explique com suas palavras**
1. O que a validação 1 verifica? Se existe o Id de número 7, preenchido.
2. O que a validação 2 verifica? Se está preenchido o campo nome ( name ).
3. O que a validação 3 verifica? Confirma que o campo nome ( name ) NÃO está vazio.
4. O que a validação 4 verifica? Se o campo altura ( height ), está preenchido.

### 3.2 Complete as validações

**Tarefa:** execute o bloco abaixo. Ele já está funcionando. Depois, alterem as expressões se o professor pedir outra nave ou outro endpoint. Em seguida, expliquem por que cada validação faz sentido para QA.
"""

url = "https://swapi.dev/api/starships/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

print("Status 200:", response.status_code == 200)

# Os exemplos abaixo já estão corretos e executáveis.
# Se o professor pedir, vocês podem alterar para validar outros campos.
print("Campo 'name' existe:", "name" in dados)
print("Campo 'model' existe:", "model" in dados)
print("Nome não está vazio:", dados["name"] != "")

"""**Explique com suas palavras**
1. Explique a validação 1? Porque se estiver vazio, ele avisará com um erro ( 404 - Not found ).
2. Explique a validação 2? Porque o campo nome ( name ) é para saber sobre quem ou qual o nome que está vinculado ao Id.
3. Explique a validação 3 ? Porque o modelo é a categoria em que a nave se encaixa.
4. Explique a validação 4? Porque se o nome estiver vazio, deverá olhar para saber o que está errado e se realmente está preenchido.

## Parte 4 — Testes automatizados com assert

Agora vocês vão trabalhar sobre scripts já prontos. Os asserts abaixo já executam sem erro. A tarefa do grupo é **entender o que cada linha valida**, ajustar se o professor pedir outro recurso e registrar as respostas.

### 4.1 Assert no personagem

**Tarefa:** execute o bloco. Depois, expliquem o que cada assert valida e, se quiserem, alterem o endpoint para outro personagem.
"""

url = "https://swapi.dev/api/people/27/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado" # Se o Status Code, bate corretamente ou não.
assert "name" in dados, "Erro: campo name não encontrado" # Se o campo nome será encontrado ou não.
assert dados["name"] != "", "Erro: nome vazio" # Se o campo nome está preenchido ou não.

print("Todos os testes do personagem passaram!")

"""### 4.2 Assert na nave

**Tarefa:** execute o bloco. Depois, descrevam qual campo foi validado em cada assert e proponham mais 1 validação extra em Markdown.

"""

url = "https://swapi.dev/api/starships/13/"
response, origem = buscar_endpoint(url)
dados = response.json()

assert response.status_code == 200, "Erro: status inesperado" # Campo Status Code.
assert "manufacturer" in dados, "Erro: fabricante não encontrado" # Campo Fabricante.
assert dados["model"] != "", "Erro: modelo vazio" # Campo Modelo, em resumo, todos foram validados

# Validar que o campo max_atmosphering_speed da nave não está vazio:
assert dados["max_atmosphering_speed"] != "", "Erro: Maxima atmosfera da velocidade da nave vazio"


print("Todos os testes da nave passaram!")

"""## Parte 5 — Cenário negativo

Agora você vai observar como a API se comporta quando pedimos um recurso inexistente.
"""

url = "https://swapi.dev/api/people/9999/"
response, origem = buscar_endpoint(url)

print("Origem dos dados:", origem)
print("Status Code:", response.status_code)
print("Texto retornado:")
print(response.text)

"""**Perguntas**
1. Qual status code foi retornado? 404 ( Not Found ).
2. Esse comportamento está correto? Sim.
3. Por que um QA deve testar cenários negativos? Porque se não testar os cenários negativos não saberá os erros do sistema criado ou os acertos ( Exemplo: O Id 9999 não tem um cadastro, automaticamente ele tem que dar erro ).

## Parte 6 — Mini desafio final

Agora você vai alterar apenas o endpoint da função abaixo e gerar um pequeno resumo.
"""

def resumo_recurso(url):
    response, origem = buscar_endpoint(url)
    print("Origem dos dados:", origem)
    print("Status Code:", response.status_code)

    if response.status_code != 200:
        print("Recurso não encontrado.")
        return

    dados = response.json()

    for chave, valor in dados.items():
        print(f"{chave}: {valor}")

# ALTERE O ENDPOINT ABAIXO PARA TESTAR OUTRO RECURSO
resumo_recurso("https://swapi.dev/api/planets/14/")

"""**Respostas finais**
1. Qual endpoint você testou no desafio? https://swapi.dev/api/planets/14/
2. Qual foi o status code? 200
3. Qual campo chamou mais a sua atenção? Diametro ( Diameter ).
4. Se você fosse QA, quais 3 validações faria nesse recurso?
1 - Validaria se o status_code é 200, confirmando que o recurso foi encontrado com sucesso.
2 - Validaria se os campos obrigatórios existem no JSON retornado.
3 - 3. Validaria se o campo nome é "Kashyyyk", se o campo população contém apenas dígitos e se o campo clima não está vazio.

# Entrega da atividade

Entreguem:

1. O notebook preenchido  
2. As respostas em Markdown  
3. Os scripts ajustados  
4. Os asserts analisados e/ou adaptados  
5. Uma conclusão curta do grupo: **quais foram as 3 validações mais importantes?**

## Fechamento
Ao final desta atividade, vocês praticaram:

- leitura de resposta JSON
- análise de status code
- validação de campos
- pensamento de QA
- testes simples com assert
- análise de cenário negativo
"""